import type { Db } from "../client";
import { type NewCheckin, type NewQuestion, checkins } from "../schema";
export declare function insertCheckin(db: Db, data: NewCheckin): {
    id: string;
    status: "pending" | "answered" | "skipped" | "timeout";
    createdAt: number;
    sessionId: string;
    completedAt: number | null;
    trigger: "timer" | "urgent" | "manual" | "completion" | "compaction";
    summary: string;
    discordMessageId: string | null;
};
export declare function updateCheckin(db: Db, id: string, data: Partial<Omit<typeof checkins.$inferSelect, "id" | "createdAt">>): void;
export declare function getCheckins(db: Db, sessionId: string): {
    id: string;
    status: "pending" | "answered" | "skipped" | "timeout";
    createdAt: number;
    sessionId: string;
    completedAt: number | null;
    trigger: "timer" | "urgent" | "manual" | "completion" | "compaction";
    summary: string;
    discordMessageId: string | null;
}[];
export declare function insertQuestion(db: Db, data: NewQuestion): void;
export declare function answerQuestion(db: Db, id: string, answer: string): void;
export declare function updateQuestionCheckin(db: Db, id: string, checkinId: string): void;
export declare function getPendingQuestions(db: Db, sessionId: string): {
    text: string;
    id: string;
    createdAt: number;
    sessionId: string;
    checkinId: string | null;
    context: string | null;
    suggestions: string | null;
    answer: string | null;
    isUrgent: boolean;
    answeredAt: number | null;
}[];
export declare function getQuestions(db: Db, sessionId: string): {
    text: string;
    id: string;
    createdAt: number;
    sessionId: string;
    checkinId: string | null;
    context: string | null;
    suggestions: string | null;
    answer: string | null;
    isUrgent: boolean;
    answeredAt: number | null;
}[];
